import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import NavBar from '@/app/components/NavBar'
import Footer from './components/Footer'

const poppins = Poppins({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  style: 'normal'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <nav>
          <NavBar />
        </nav>
          {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
